version: '3.8'

services:
  github-manager:
    build: .
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - GITHUB_ORG=${GITHUB_ORG}
    volumes:
      - ./.env:/app/.env:ro
      - ./config:/app/config:ro
